from fastapi.testclient import TestClient

from app.main import app

client = TestClient(app)


def test_multi_connection_takeover_does_not_block_reconnects():
    session_id = "test-session-123"
    conn_id_1 = "conn-1"
    conn_id_2 = "conn-2"

    # 1. Initialize first connection
    resp1 = client.post(
        "/session", json={"sessionId": session_id, "connectionId": conn_id_1}
    )
    assert resp1.status_code == 200
    data1 = resp1.json()
    assert data1["alreadyActive"] is False

    # 2. A new connection for the same session can be a normal browser or
    # Chainlit reconnect, so it should replace the old connection instead of
    # showing a duplicate-tab page.
    resp2 = client.post(
        "/session", json={"sessionId": session_id, "connectionId": conn_id_2}
    )
    assert resp2.status_code == 200
    data2 = resp2.json()
    assert data2["alreadyActive"] is False

    # 3. Deregister first connection
    resp3 = client.post(
        "/session/deregister", json={"sessionId": session_id, "connectionId": conn_id_1}
    )
    assert resp3.status_code == 200

    # 4. Attempt second connection again (should now be allowed)
    resp4 = client.post(
        "/session", json={"sessionId": session_id, "connectionId": conn_id_2}
    )
    assert resp4.status_code == 200
    data4 = resp4.json()
    assert data4["alreadyActive"] is False


def test_same_connection_reinit_allowed():
    session_id = "test-session-456"
    conn_id = "conn-unique"

    # Initialize
    resp1 = client.post(
        "/session", json={"sessionId": session_id, "connectionId": conn_id}
    )
    assert resp1.status_code == 200
    assert resp1.json()["alreadyActive"] is False

    # Re-initialize same connection (e.g. refresh)
    # Actually, on refresh a new conn_id should be generated by the frontend,
    # but let's test that the SAME conn_id is also fine (idempotent).
    resp2 = client.post(
        "/session", json={"sessionId": session_id, "connectionId": conn_id}
    )
    assert resp2.status_code == 200
    assert resp2.json()["alreadyActive"] is False


def test_multi_tab_behavior_with_empty_conn_id():
    session_id = "test-session-789"

    # 1. Initialize without conn_id (should be allowed, but won't block others)
    resp1 = client.post("/session", json={"sessionId": session_id})
    assert resp1.status_code == 200
    assert resp1.json()["alreadyActive"] is False

    # 2. Initialize with conn_id
    resp2 = client.post(
        "/session", json={"sessionId": session_id, "connectionId": "conn-1"}
    )
    assert resp2.status_code == 200
    assert resp2.json()["alreadyActive"] is False

    # 3. Initialize another with different conn_id. This is allowed because
    # server-side connection ids are not stable enough to prove a duplicate tab.
    resp3 = client.post(
        "/session", json={"sessionId": session_id, "connectionId": "conn-2"}
    )
    assert resp3.status_code == 200
    assert resp3.json()["alreadyActive"] is False
